backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# These lines should *not* be indented
media_folder: "src/assets/images/uploads" 
public_folder: "/images/uploads" 

collections:

  # Images for portfolio page
  - name: "portfolio-image"
    label: "Image"
    folder: "src/assets/images/image-for-portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "ID", name: "id", widget: "number"}
      - {label: "Image", name: "image", widget: "image"}

  # Photo album
  - name: "photo-album"
    label: "Photo album"
    folder: "src/content/photo-albums"
    create: true
    slug: "{{year}} - {{month}} - {{day}} - '{{slug}}'"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Year", name: "date", widget: "datetime"}
      - {label: "Album description", name: "description", widget: "text"} 

  # Test
  # - name: "test-field"
  #   label: "Test"
  #   create: true
  #   folder: "src/content/photo-albums"
  #   format: "json"
  #   slug: "{{slug}}"
  #   fields:
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Year", name: "date", widget: "datetime"}
  #     - {label: "Album description", name: "description", widget: "text"} 

  # Test 2
  # - name: "test-field 2"
  #   label: "Test two"
  #   create: true
  #   file: "src/content"
  #   format: "json"
  #   slug: "{{slug}}"
  #   fields:
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Year", name: "date", widget: "datetime"}
  #     - {label: "Album description", name: "description", widget: "text"} 

  # Test 3
  # - name: test
  #   label: Test
  #   format: "json"
  #   file: "src/content/photo-albums.json" # this only makes sense for file collections
  #   field: [{ name: title, label: Title, widget: string }, { name: description, label: Description, widget: string}]

  - name: "photo-albums"
    label: "Albums"
    files:
    - label: "Album"
      name: "album"
      file: "src/content/photo-albums.json"
      widget: "list"
      fields:
        - label: "Album"
          name: "album"
          widget: "object"
          fields:
          - { label: "Title", name: "title", widget: "string"}
          - { label: "Description", name: "description", widget: "string"}




