backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# These lines should *not* be indented
media_folder: "public/images/uploads" 
public_folder: "/images/uploads" 

media_library:
  name: cloudinary
  config: 
    cloud_name: ddxnrgllz
    api_key: 314693828169891

collections:
  - label: "Images for portfolio"
    name: "portfolio-images"
    files: 
      - label: "Images for portfolio"
        name: "Image"
        file: "src/assets/images/images-for-portfolio/portfolio-images.json"
        fields:
          - label: "Image"
            name: "image_list"
            widget: "list"
            fields:
              - {label: "ID (1 = Car, 2 = People, 3 = Nature)", name: "id", widget: "number"}
              - {label: "Image", name: "image", widget: "image"}

  # Photo albums
  - label: "Photo album"
    name: "photo-album"
    files: 
      - label: "Albums"
        name: "album"
        file: "src/content/photo-albums.json"
        fields:
          - label: "Album"
            name: "album_list"
            widget: "list"
            fields:
              - {label: "ID", name: "id", widget: "ncw-id", hint: "This is the album ID"}
              - {label: "Album title", name: "title", widget: "string"}
              - {label: "Year", name: "year", widget: number}
              - {label: "Camera", name: "camera", widget: "string"}
              - {label: "Camera lens", name: "camera_lens", widget: "string"}
              - {label: "Album description", name: "description", widget: "text"}
              - {label: "Album cover image", name: "cover_image", widget: "image"}
              - {label: "Albums images", name: "images", widget: "image", media_library: { name: cloudinary, output_filename_only: true, config: { multiple: true } }}
    







