backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# These lines should *not* be indented
media_folder: "src/assets/images/uploads" 
public_folder: "/images/uploads" 

collections:

  # Images for portfolio page
  # - name: "portfolio-image"
  #   label: "Image"
  #   folder: "src/assets/images/image-for-portfolio"
  #   create: true
  #   slug: "{{slug}}"
  #   fields:
  #     - {label: "ID", name: "id", widget: "number"}
  #     - {label: "Image", name: "image", widget: "image"}

  - label: "Images for portfolio"
    name: "portfolio-images"
    files: 
      - label: "Images for portfolio"
        name: "Image"
        file: "src/assets/images/images-for-portfolio/portfolio-images.json"
        fields:
          - label: "Image"
            name: "image_list"
            widget: "list"
            fields:
              - {label: "ID", name: "id", widget: "number"}
              - {label: "Image", name: "image", widget: "image"}

  # Photo albums
  - label: "Photo album"
    name: "photo-album"
    files: 
      - label: "Albums"
        name: "album"
        file: "src/content/photo-albums.json"
        fields:
          - label: "Album"
            name: "album_list"
            widget: "list"
            fields:
              - {label: "Album title", name: "title", widget: string}
              - {label: "Year", name: year, widget: number}
              - {label: "Album description", name: "description", widget: text}





