backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# These lines should *not* be indented
media_folder: "public/images/uploads" 
public_folder: "/images/uploads" 

media_library:
  name: cloudinary
  config: 
    cloud_name: ddxnrgllz
    api_key: 314693828169891

collections:
  - label: "Images for portfolio"
    name: "portfolio-images"
    files: 
      - label: "Images for portfolio"
        name: "Image"
        file: "src/assets/images/images-for-portfolio/portfolio-images.json"
        fields:
          - label: "Image"
            name: "image_list"
            widget: "list"
            fields:
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Image category", name: "tag", widget: "select", options: ["car", "nature", "architecture", "people"], hint: "Choose in what category your chosen image needs to be"}

  # Photo albums
  - label: "Photo album"
    name: "photo-album"
    files: 
      - label: "Albums"
        name: "album"
        file: "src/content/photo-albums.json"
        fields:
          - label: "Album"
            name: "album_list"
            widget: "list"
            fields:
              - {label: "ID", name: "id", widget: "ncw-id", hint: "The album ID is auto-generated, pureley for back-end purposes"}
              - {label: "Album title", name: "title", widget: "string"}
              - {label: "Year", name: "year", widget: number}
              - {label: "Camera", name: "camera", widget: "string"}
              - {label: "Camera lens", name: "camera_lens", widget: "string"}
              - {label: "Album cover image", name: "cover_image", widget: "image", hint: "*Make sure the cover image has the aspect ratio of an portrait. Only this way it can be displayed properly on the site*", hint: "The album cover is used on the home page, displayed beneath the short introduction"}
              - {label: "Albums images", name: "images", widget: "image", hint: "These images will be displayed on the page of the album it self, you can select multiple (obviously)", media_library: { name: cloudinary, output_filename_only: true, config: { multiple: true } }}
              - label: "Album description paragraph"
                name: "album_description_paragraphs"
                widget: "list"
                fields:
                  - {label: "Paragraph", name: "paragraph", widget: "text"}

  - label: "Videos for Motion page"
    name: "motion-videos"
    files: 
      - label: "Video for Motion page"
        name: "Video"
        file: "src/assets/videos/motion-videos.json"
        fields:
          - label: "Image"
            name: "video_projects_list"
            widget: "list"
            fields:
              - {label: "Video title", name: "title", widget: "string"}
              - {label: "Video description", name: "description", widget: "string"}
              - {label: "Video file", name: "video_url", widget: "file"}

 
    







